// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcgozfkrxsnrkxgszndj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjZ296ZmtyeHNucmt4Z3N6bmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNTUxNjAsImV4cCI6MjA1NTczMTE2MH0.eKYnci_BAVcYfq5lVYem-qv8aUB41UBENdndREtmdjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);